# https://garagehq.deuxfleurs.fr/api/garage-admin-v0.html

metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

replication_mode = "1"
compression_level = 2

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "0.0.0.0:3901"
# Generate with: openssl rand -hex 32
rpc_secret = "c9113d69fda5853f73471e1f08f3e1e01f3bdf316240de009e082c6c10b31340"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "s3AdminToken"
metrics_token = "s3MetricsToken"

[k2v_api]
api_bind_addr = "[::]:3904"
