version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2023-06-23T20-26-00Z
    container_name: minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data/minio'
    command: minio server --address ":9000" /data/minio --console-address ":9001"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      retries: 3
      timeout: 5s
    environment:
      MINIO_ROOT_USER: 's3admin'
      MINIO_ROOT_PASSWORD: 's3passw0rd'

  minio-mc:
    image: minio/mc
    container_name: minio_mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set mys3 http://minio:9000 s3admin s3passw0rd;
      /usr/bin/mc mb mys3/fuelstack;
      /usr/bin/mc policy set public mys3/fuelstack;
      exit 0;
      "

volumes:
  minio_data:
    driver: local
