# yaml-language-server: $schema = https://taskfile.dev/schema.json

version: "3"

vars:
  APP_VERSION: '{{.APP_VERSION | default "1.0.0"}}'
  GIT_SHA: {sh: git rev-parse --short HEAD}
  ROOT_DIR: {sh: pwd}

tasks:
  prepare:
    cmds: ['docker-compose -f docker-compose.yml up -d']

  cleanup:
    cmds: ['docker-compose down --remove-orphans', 'pnpm turbo clean']

  dev:api:
    desc: Start development Fastify API
    cmds: ['pnpm turbo dev --no-cache --continue --filter=api...']

  dev:admin:
    desc: Start development Admin (including API)
    cmds: ['pnpm turbo dev --no-cache --continue --filter={api,admin}...']

  dev:website:
    desc: Start development Website (including API)
    cmds: ['pnpm turbo dev --no-cache --continue --filter={api,website}...']

  dev:blog:
    desc: Start development Blog (including API)
    cmds: ['pnpm turbo dev --no-cache --continue --filter={api,blog}...']
